name: "S3 Sync"
description: "Sync a directory to an AWS S3 repository"
author: jakejarvis
outputs:
  data:
    description: "Command output from aws s3 sync"
    value: ${{ steps.sync.outputs.data }}
runs:
  using: docker
  image: Dockerfile
branding:
  icon: refresh-cw
  color: green
